name: Pack Chrome Extension

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Build
        run: |
          ${{steps.setup-chrome.outputs.chrome-path}} --pack-extension=./chrome-src

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            chrome-src.crx
