name: Pack Chrome Extension

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Build
        run: |
          ${{steps.setup-chrome.outputs.chrome-path}} --pack-extension=./chrome-src --no-sandbox
          mv chrome-src.crx chrome-trlfix.crx
          ls -l

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{github.ref}}
          tag_name: ${{github.ref}}
        env:
          GITHUB_TOKEN: ${{github.token}}
      - name: upload file
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chrome-trlfix.crx
          asset_name: chrome-trlfix.crx
          asset_content_type: application/x-chrome-extension
